### ISSUE TITLE
problem with virtual pagination height

### ISSUE THREAD

**Issue by masterkain** [matfish2/vue-tables-2#970]
- Vue.js version: 3
- consumed using: vite / tailwind

`.use(ClientTable, {}, "tailwind")`

so we have a very basic table with tailwind theme, we followed instructions https://matanya.gitbook.io/vue-tables-2/virtual-pagination

1) we don't see the `VueTables__wrapper` anywhere
2) we specified that max-height on a wrapper class

however on first load, when the browser viewport is bigger than the limit specified, the table would not show the rest of records, requiring a resize first.

is it something that can be fixed with css on our side? for now I have raised `perPage` to circumvent this issue.

https://user-images.githubusercontent.com/12844/133908612-df5f843f-1a4b-4e68-ac3e-632aca79ce40.mp4

**Comment by matfish2** [comment]
Thanks for raising the issue. I have added `VueTables__wrapper` to the latest version (0.4.1). Alternatively, you can target `table-responsive` on the current version (0.4.0). I have updated the docs with an additional CSS rule, namely `overflow-y: scroll`, which appears to be necessary for tailwind. Tested locally and it seems to work.

**Comment by masterkain** [comment]
thank you very much for the input, I still have trouble with some logic

some tests:

```
.table-responsive {
  /* @apply h-screen; */
  /* @apply h-4/5; */
  max-height: 500px; // even 1500px;
  @apply overflow-y-scroll;
}
```

while the behavior is slightly different I still have the issue on first page load.
are you aware of any trick to expand the table height on initial page load to take the entire viewport?

![Screenshot 2021-09-18 at 23 53 58](https://user-images.githubusercontent.com/12844/133909526-19431789-9aa6-44c9-bef2-e4c05cd7934a.png)

**Comment by matfish2** [comment]
I think this should do the trick:
```css
min-height: calc(100vh - 100px); // or whatever you want to deduct from total viewport height
```

**Comment by masterkain** [comment]
thanks for another input, I tried but I cannot get it work properly, maybe I need to recheck the classes of my other containers.

given that this issue might not be 100% of vue-tables-2 can I reach you on xscode for that support hour? thanks, feel free to close in case.

**Comment by masterkain** [comment]
for the record this is what happens with the min-height calculation, it's very close to what I'm trying to do but records are not loaded, maybe just up perPage at this point?

https://user-images.githubusercontent.com/12844/133910143-ad7bb533-aded-455a-9af0-902c3dfc9b68.mp4

**Comment by matfish2** [comment]
For

**Comment by matfish2** [comment]
Yes, for records to be loaded the items per page must exceed the table viewport, so if you want the table to span the entire height of the viewport you need to set a per page accordingly.
